anguage: java

addons:
  sonarcloud:
    organization: "SalyND"

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=SalyND-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=eef77e848c90723d753021de2907eb615f851551 -Dsonar.projectKey=Cours-java-340 -Dsonar.branch=master
