language: java

addons: 
  sonarcloud:
    organization: "salynd-github"
		
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=salynd-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=Cours-Java-340 -Dsonar.branch=master -Dsonar.login=eef77e848c90723d753021de2907eb615f851551